### PR TITLE
Block width output

### PR DESCRIPTION
**Pull request by alhom**

### CODE REVIEW

**Comment by ykempf** [comment]
Why is this not showing only the last commit? I just merged fmihpc/dev and pushed to my branch.

**Comment by ykempf** [comment]
And maybe call it velocity_block_width?

**Comment by alhom** [comment]
I think you hadn't yet merged dev when I made the PR? I'll try redoing this one.

**Comment by ykempf** [comment]
But shouldn't it dynamoically update if any of the two branches change??

**Comment by alhom** [comment]
I guess it should, but didn't? Even with the fresh commit... 🤷

**Pull request closed without merging**
